#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_tf_example_from_raw_img": "01_data.load.ipynb",
         "get_tf_example_from_numpy": "01_data.load.ipynb",
         "store_np_imgs_as_tfrecord": "01_data.load.ipynb",
         "parse_tf_example_img": "01_data.load.ipynb",
         "read_tfrecord_as_dataset": "01_data.load.ipynb",
         "get_cifar10": "02_data.datasets.ipynb",
         "train_model": "03_train.ipynb"}

modules = ["data/load.py",
           "data/datasets.py",
           "train.py"]

git_url = "https://github.com/unography/unoai/tree/master/"

def custom_doc_links(name): return None