# AUTOGENERATED! DO NOT EDIT! File to edit: dev/04_vision.augmentations.ipynb (unless otherwise specified).

__all__ = ['cutout']

# Cell
from ..imports import *

# Cell
def cutout(img, h: int,w: int):
    shape = tf.shape(img)
    height = shape[0]; width = shape[1]
    x1 = tf.random.uniform([], 0, height+1 - h, tf.int32)
    y1 = tf.random.uniform([], 0, width+1 - w, tf.int32)
    img1 = tf.ones_like(img)
    cut_slice = tf.slice(img1,[x1, y1, 0],[h, w, 3])
    mask = tf.image.pad_to_bounding_box([cut_slice],x1,y1,height,width)
    mask = tf.ones_like(mask) - mask
    return tf.multiply(img,mask)[0]